CC=g++
CFLAGS=-pedantic-errors -g
SOURCES=biginteger.cpp
EXECUTABLE=biginttest

all: $(SOURCES) $(EXECUTABLE)

$(EXECUTABLE):
	$(CC) $(SOURCES) $(CFLAGS) -o $@

clean:
	cmd //C del *.o $(EXECUTABLE).exe